### ISSUE TITLE
Recently asked questions company wise list

### ISSUE THREAD

**Issue by may12day** [ssavi-ict/LeetCode-Which-Company#229]
Can you add the feature where we can find particular company's recently asked questions in 6 months, 1 year etc. with their frequencies?

**Comment by ssavi-ict** [comment]
Hello Mayank,
First of all, Thank You so much for using the extension. I appreciate your request to make this extension even better. 

I thought about this feature. Since I crowd-source the company information from the web, it is hard to look up the recent interview information. Moreover, this is more of a user contribution-oriented feature. Like LeetCode does.

However, I will try to implement this feature at least for the information I can collect from the web. It may take some though. Again appreciate for reaching out.

**Comment by pranavcool007** [comment]
is this list latest ?

**Comment by ssavi-ict** [comment]
> is this list latest ?

Hello Pranav, I usually collect the company information from the web. So it is tough to determine the recency. However, I try to collect as much recent data as possible.

**Comment by ssavi-ict** [comment]
@may12day, Released v1.0.8 that shows the recent companies who asked a certain question. Hopefully, in the next release, I will try to include the **Recently asked company-wise question list**. However, I am not quite sure if I can add the frequency part. Hope you understand the concern.

Thank You
